name: Branch Preview Builder

on:
  push:
    branches-ignore:
      - main

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare preview folder
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF##*/}" | tr '[:upper:]' '[:lower:]')
          mkdir -p previews/$BRANCH_NAME
          rsync -av --exclude='previews' --exclude='.git' ./ previews/$BRANCH_NAME/

      - name: Generate index.html
        run: node generate-index.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./previews
